# Generated by Django 2.2.4 on 2019-08-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import installer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(choices=[('Engineer', 'Engineer'), ('Technician', 'Technician'), ('Support', 'Support'), ('Rep', 'Rep'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=20)),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=installer.models.upload_location)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invited_installers', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_installers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
