# Generated by Django 2.2.4 on 2019-08-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('model_no', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Generator',
                'verbose_name_plural': 'Generators',
                'ordering': ['plant__plant_no', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('headquarters', models.CharField(max_length=30)),
                ('extra_info', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=20)),
                ('extra_info', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runnings', to='plant.Gen')),
            ],
            options={
                'verbose_name_plural': 'Running',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_no', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('original_no', models.CharField(blank=True, max_length=20)),
                ('location', models.TextField(max_length=300)),
                ('town_city', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='client.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_plants', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plants', to='plant.LGA')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_plants', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plants', to='plant.State')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lgas', to='plant.State'),
        ),
        migrations.AddField(
            model_name='gen',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gens', to='plant.Plant'),
        ),
    ]
