# Generated by Django 2.2.4 on 2019-08-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import temp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Installer', 'Installer'), ('Master', 'Master'), ('Admin', 'Admin'), ('Agent', 'Agent')], default='Installer', max_length=15)),
                ('used', models.BooleanField(default=False)),
                ('cv', models.FileField(blank=True, null=True, upload_to=temp.models.upload_location)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(choices=[('Installer', 'Installer'), ('Master', 'Master'), ('Admin', 'Admin'), ('Agent', 'Agent')], default='Installer', max_length=15)),
                ('used', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=254)),
                ('inviter_id', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
