# Generated by Django 2.2.4 on 2019-08-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('Cylinderical', 'Cylinderical'), ('Rectangular', 'Rectangular'), ('Elliptical', 'Elliptical'), ('Other', 'Other')], default='Cylinderical', max_length=20)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('major_diameter', models.FloatField(blank=True, null=True)),
                ('minor_diameter', models.FloatField(blank=True, null=True)),
                ('diameter', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='meter', max_length=15)),
                ('alignment', models.CharField(choices=[('Horizontal', 'Horizontal'), ('Vertical', 'Vertical'), ('Neither', 'Neither')], default='Horiontal', max_length=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_configurations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, default='liter', max_length=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tank.models.upload_location)),
                ('configuration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tank.Configuration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_tanks', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_tanks', to=settings.AUTH_USER_MODEL)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tank.Tank')),
            ],
            options={
                'verbose_name_plural': 'Volume',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=600)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smses', to='tank.Tank')),
            ],
            options={
                'verbose_name_plural': 'SMS',
                'ordering': ['-date_received'],
            },
        ),
    ]
